#!/bin/bash

# Description: File Utilities Library

# Log Levels
LOG_LEVEL_INFO="INFO"
LOG_LEVEL_WARNING="WARNING"
LOG_LEVEL_ERROR="ERROR"

function check_if_directory_exists () {

    if [ $# -ne 1 ]
    then
        log $LOG_FILE $LOG_LEVEL_ERROR $LOG_TAG 'Invalid number of arguments.'
        log $LOG_FILE $LOG_LEVEL_INFO $LOG_TAG "Usage: check_if_directory_exists 'path/to/directory'"
        exit 1
    fi

    DIRECTORY="$1"
    if [ ! -d "$DIRECTORY" ]; then
        log $LOG_FILE $LOG_LEVEL_ERROR $LOG_TAG "Path does not exist [path=$DIRECTORY]."
        exit 1
    fi
}
