#!/bin/bash

# Description: Script to remove duplicate entries from .bash_history file.
# Note:
# 1. Duplicates will still be created in .bash_history file due to histappend
#    Hence the need for this script.

# Remove duplicates while preserving input order
function dedup {
   awk '! x[$0]++' $@
}

# Removes $HISTIGNORE commands from input
function remove_histignore {
   if [ -n "$HISTIGNORE" ]; then
      # replace : with |, then * with .*
      local IGNORE_PAT=`echo "$HISTIGNORE" | sed s/\:/\|/g | sed s/\*/\.\*/g`
      # negated grep removes matches
      grep -vx "$IGNORE_PAT" $@
   else
      cat $@
   fi
}

# Clean up the history file by remove duplicates and commands matching
# $HISTIGNORE entries
function bash_history_cleanup {
   local HISTFILE_SRC=~/.bash_history
   local HISTFILE_DST=/tmp/.$USER.bash_history.clean
   if [ -f $HISTFILE_SRC ]; then
      \cp $HISTFILE_SRC $HISTFILE_SRC.backup
      dedup $HISTFILE_SRC | remove_histignore >| $HISTFILE_DST
      \mv $HISTFILE_DST $HISTFILE_SRC
      chmod go-r $HISTFILE_SRC
      history -c
      history -r
   fi
}

# Export function that can be called like below
# export -f bash_history_cleanup

# Call the function
bash_history_cleanup
echo '.bash_history file deduplicated successfully!'
